# Generated by Django 5.0.6 on 2024-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='date_buyed',
            field=models.DateTimeField(null=True),
        ),
    ]
