# Generated by Django 5.0.6 on 2024-07-11 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_blacklist',
            field=models.ManyToManyField(related_name='blacklisted_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
